#!/bin/bash

# Get ATDM_CONFIG_SCRIPT_DIR
CURRENT_SCRIPTS_DIR=`echo $BASH_SOURCE | sed "s/\(.*\)\/.*\.sh/\1/g"`
ATDM_CONFIG_SCRIPT_DIR=`readlink -f ${CURRENT_SCRIPTS_DIR}/../..`

#
# Define the unit tests
#

testDefault() {
  ATDM_CONFIG_BUILD_NAME=default
  . ${ATDM_CONFIG_SCRIPT_DIR}/utils/set_build_options.sh
  ${_ASSERT_EQUALS_} ${ATDM_CONFIG_COMPILER} DEFAULT
  ${_ASSERT_EQUALS_} ${ATDM_CONFIG_KOKKOS_ARCH} DEFAULT
  ${_ASSERT_EQUALS_} ${ATDM_CONFIG_BUILD_TYPE} DEBUG
  ${_ASSERT_EQUALS_} ${ATDM_CONFIG_SHARED_LIBS} OFF
  ${_ASSERT_EQUALS_} ${ATDM_CONFIG_NODE_TYPE} SERIAL
  ${_ASSERT_EQUALS_} ${ATDM_CONFIG_USE_OPENMP} OFF
  ${_ASSERT_EQUALS_} ${ATDM_CONFIG_USE_CUDA} OFF
  ${_ASSERT_EQUALS_} ${ATDM_CONFIG_USE_PTHREADS} OFF
}

#
# Run the unit tests
#

. ${ATDM_CONFIG_SCRIPT_DIR}/shunit2/shunit2
